### ISSUE TITLE
`LoginBroadcast` sometimes fail.

### ISSUE THREAD

**Issue by JoshuaLight** [JoshuaLight/Eternity#229]
Here is the log:
[ 5/2/2018 9:24:11 PM ]  Server is started at 127.0.0.1:12346.
[ 5/2/2018 9:24:11 PM ]  Receiving courier.
[ 5/2/2018 9:24:11 PM ]  Server is stopped at 127.0.0.1:12346.
[ 5/2/2018 9:24:11 PM ]  Failed to accept courier: The operation was canceled.
   at Eternity.TcpListenerExtensions.<AcceptClientAsync>d__0.MoveNext() in C:\git\Eternity\Src\Eternity.Solution\Core\Common\Extensions\TcpListenerExtensions.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Eternity.Network.TcpListenerDelivery`1.<Courier>d__5.MoveNext() in C:\git\Eternity\Src\Eternity.Solution\Core\Common\Network\Deliveries\TcpListenerDelivery.cs:line 27
[ 5/2/2018 9:24:11 PM ]  Server is started at 127.0.0.1:12347.
[ 5/2/2018 9:24:11 PM ]  Receiving courier.
[ 5/2/2018 9:24:11 PM ]  Courier [ Binary ] [ Packet ] arrived.
[ 5/2/2018 9:24:11 PM ]  Receiving courier.
[ 5/2/2018 9:24:11 PM ]  Courier [ Binary ] [ Packet ] arrived.
[ 5/2/2018 9:24:11 PM ]  Receiving packet.
[ 5/2/2018 9:24:11 PM ]  Receiving courier.
[ 5/2/2018 9:24:11 PM ]  Receiving packet.
[ 5/2/2018 9:24:11 PM ]  Courier [ Binary ] [ Packet ] arrived.
[ 5/2/2018 9:24:11 PM ]  Receiving packet.
[ 5/2/2018 9:24:11 PM ]  Failed to receive: Operation was cancelled.
[ 5/2/2018 9:24:11 PM ]  Failed to receive: A task was canceled.
[ 5/2/2018 9:24:11 PM ]  Server is stopped at 127.0.0.1:12347.
[ 5/2/2018 9:24:11 PM ]  Receiving courier.
[ 5/2/2018 9:24:11 PM ]  Failed to receive: A task was canceled.
[ 5/2/2018 9:24:11 PM ]  Server is started at 127.0.0.1:12348.
[ 5/2/2018 9:24:11 PM ]  Receiving courier.
[ 5/2/2018 9:24:11 PM ]  Failed to accept courier: Not listening. You must call the Start() method before calling this method.
   at System.Net.Sockets.TcpListener.BeginAcceptTcpClient(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Net.Sockets.TcpListener.AcceptTcpClientAsync()
   at Eternity.TcpListenerExtensions.<AcceptClientAsync>d__0.MoveNext() in C:\git\Eternity\Src\Eternity.Solution\Core\Common\Extensions\TcpListenerExtensions.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Eternity.Network.TcpListenerDelivery`1.<Courier>d__5.MoveNext() in C:\git\Eternity\Src\Eternity.Solution\Core\Common\Network\Deliveries\TcpListenerDelivery.cs:line 27
[ 5/2/2018 9:24:12 PM ]  Failed to accept courier: Not listening. You must call the Start() method before calling this method.
   at System.Net.Sockets.TcpListener.BeginAcceptTcpClient(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Net.Sockets.TcpListener.AcceptTcpClientAsync()
   at Eternity.TcpListenerExtensions.<AcceptClientAsync>d__0.MoveNext() in C:\git\Eternity\Src\Eternity.Solution\Core\Common\Extensions\TcpListenerExtensions.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Eternity.Network.TcpListenerDelivery`1.<Courier>d__5.MoveNext() in C:\git\Eternity\Src\Eternity.Solution\Core\Common\Network\Deliveries\TcpListenerDelivery.cs:line 27
[ 5/2/2018 9:24:12 PM ]  Server is stopped at 127.0.0.1:12348.
[ 5/2/2018 9:24:12 PM ]  Login_ShoulReturnResultMessage.Start
[ 5/2/2018 9:24:12 PM ]  Server is started at 127.0.0.1:12349.
[ 5/2/2018 9:24:12 PM ]  Receiving courier.
[ 5/2/2018 9:24:12 PM ]  Courier [ Binary ] [ Packet ] arrived.
[ 5/2/2018 9:24:12 PM ]  Sending [ Login | Test ] packet.
[ 5/2/2018 9:24:12 PM ]  Receiving courier.
[ 5/2/2018 9:24:12 PM ]  Receiving packet.
[ 5/2/2018 9:24:12 PM ]  Received [ Login | Test ].
[ 5/2/2018 9:24:12 PM ]  Received Login message.
[ 5/2/2018 9:24:12 PM ]  Receiving packet.
[ 5/2/2018 9:24:12 PM ]  Spawning object [ FakeEntity #0 ] [ Player Test ] [ Living ] [ Digestion ] [ Respawn ] [ Moving ] [ HumanoidEquipment ] in world.
[ 5/2/2018 9:24:12 PM ]  Sending [ Login | Eternity.Game.Login.LoginResultMessage ] packet.
[ 5/2/2018 9:24:12 PM ]  Receiving packet.
[ 5/2/2018 9:24:12 PM ]  Received [ Login | Eternity.Game.Login.LoginResultMessage ].
[ 5/2/2018 9:24:12 PM ]  Server is stopped at 127.0.0.1:12349.
[ 5/2/2018 9:24:12 PM ]  Failed to accept courier: The operation was canceled.
   at Eternity.TcpListenerExtensions.<AcceptClientAsync>d__0.MoveNext() in C:\git\Eternity\Src\Eternity.Solution\Core\Common\Extensions\TcpListenerExtensions.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Eternity.Network.TcpListenerDelivery`1.<Courier>d__5.MoveNext() in C:\git\Eternity\Src\Eternity.Solution\Core\Common\Network\Deliveries\TcpListenerDelivery.cs:line 27
[ 5/2/2018 9:24:12 PM ]  Login_ShoulReturnResultMessage.End
[ 5/2/2018 9:24:12 PM ]  Login_ShouldBroadcastToOtherPlayers.Start
[ 5/2/2018 9:24:12 PM ]  Failed to receive: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
[ 5/2/2018 9:24:12 PM ]  Receiving courier.
[ 5/2/2018 9:24:12 PM ]  Server is started at 127.0.0.1:12350.
[ 5/2/2018 9:24:12 PM ]  Courier [ Binary ] [ Packet ] arrived.
[ 5/2/2018 9:24:12 PM ]  Sending [ Login | Test1 ] packet.
[ 5/2/2018 9:24:12 PM ]  Receiving packet.
[ 5/2/2018 9:24:12 PM ]  Receiving courier.
[ 5/2/2018 9:24:12 PM ]  Received [ Login | Test1 ].
[ 5/2/2018 9:24:12 PM ]  Received Login message.
[ 5/2/2018 9:24:12 PM ]  Receiving packet.
[ 5/2/2018 9:24:12 PM ]  Spawning object [ FakeEntity #0 ] [ Player Test1 ] [ Living ] [ Digestion ] [ Respawn ] [ Moving ] [ HumanoidEquipment ] in world.
[ 5/2/2018 9:24:12 PM ]  Sending [ Login | Eternity.Game.Login.LoginResultMessage ] packet.
[ 5/2/2018 9:24:12 PM ]  Received [ Login | Eternity.Game.Login.LoginResultMessage ].
[ 5/2/2018 9:24:12 PM ]  Sending [ Login | Test2 ] packet.
[ 5/2/2018 9:24:12 PM ]  Courier [ Binary ] [ Packet ] arrived.
[ 5/2/2018 9:24:12 PM ]  Receiving packet.
[ 5/2/2018 9:24:12 PM ]  Receiving courier.
[ 5/2/2018 9:24:12 PM ]  Receiving packet.
[ 5/2/2018 9:24:12 PM ]  Received [ Login | Test2 ].
[ 5/2/2018 9:24:12 PM ]  Received Login message.
[ 5/2/2018 9:24:12 PM ]  Receiving packet.
[ 5/2/2018 9:24:12 PM ]  Receiving packet.
[ 5/2/2018 9:24:17 PM ]  Server is stopped at 127.0.0.1:12350.
[ 5/2/2018 9:24:17 PM ]  Failed to receive: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
[ 5/2/2018 9:24:17 PM ]  Failed to accept courier: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.EndAccept(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpListener.EndAcceptTcpClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Eternity.TcpListenerExtensions.<AcceptClientAsync>d__0.MoveNext() in C:\git\Eternity\Src\Eternity.Solution\Core\Common\Extensions\TcpListenerExtensions.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Eternity.Network.TcpListenerDelivery`1.<Courier>d__5.MoveNext() in C:\git\Eternity\Src\Eternity.Solution\Core\Common\Network\Deliveries\TcpListenerDelivery.cs:line 27
[ 5/2/2018 9:24:17 PM ]  Failed to receive: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
[ 5/2/2018 9:24:17 PM ]  Failed to receive: A task was canceled.

**Comment by JoshuaLight** [comment]
I think I will close that for now.
